version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: msds_sql
    volumes:
      - msds_sql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PWD}

volumes:
  msds_sql:
    name: msds_sql
